import streamlit as st
import pandas as pd

st.set_page_config(page_title="S-OIL OA Simulator", page_icon="🛢️", layout="wide")

# =========================================================
# 1) EMBEDDED DATA
# =========================================================
# UNIT_DATA에 90개 유닛 데이터를 내장해 두어,
# 엑셀 파일 없이도 앱이 바로 동작합니다.
#
# 각 row 형식:
# {
#   "plant": "정유/윤활/아로공장",
#   "unit_code": "U-1100",
#   "unit_name": "#1 CDU",
#   "unit_desc": "설명",
#   "all": {
#       "Refinery": -0.010,
#       "#1Complex": -0.012,
#       "정유/윤활/아로공장": -0.015,
#       "HYC공장": 0.0,
#       "RFCC1공장": 0.0,
#       "#2Complex": 0.0,
#       "RFCC2공장": 0.0,
#       "아로마틱2공장": 0.0,
#       "폴리머공장": 0.0,
#   },
#   "major": {
#       "Refinery": -0.020,
#       "#1Complex": -0.022,
#       "정유/윤활/아로공장": -0.030,
#       "HYC공장": 0.0,
#       "RFCC1공장": 0.0,
#       "#2Complex": 0.0,
#       "RFCC2공장": 0.0,
#       "아로마틱2공장": 0.0,
#       "폴리머공장": 0.0,
#   }
# }

UNIT_DATA = [{'plant': '정유/윤활/아로공장',
  'unit_code': 'U-1100',
  'unit_name': '#1 CDU',
  'unit_desc': 'EDC 141,120',
  'edc': 141120,
  'complex': '#1Complex',
  'all': {'Refinery': -0.003,
          '#1Complex': -0.006,
          '정유/윤활/아로공장': -0.016,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0063,
            '#1Complex': -0.012,
            '정유/윤활/아로공장': -0.038,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-11100',
  'unit_name': '#2 CDU',
  'unit_desc': 'EDC 341,280',
  'edc': 341280,
  'complex': '#1Complex',
  'all': {'Refinery': -0.008,
          '#1Complex': -0.014,
          '정유/윤활/아로공장': -0.04,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0152,
            '#1Complex': -0.03,
            '정유/윤활/아로공장': -0.091,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-16100',
  'unit_name': '#3 CDU',
  'unit_desc': 'EDC 364,320',
  'edc': 364320,
  'complex': '#1Complex',
  'all': {'Refinery': -0.009,
          '#1Complex': -0.015,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.05,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0162,
            '#1Complex': -0.032,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': -0.079,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-41100',
  'unit_name': 'CFU',
  'unit_desc': 'EDC 131,040',
  'edc': 131040,
  'complex': '#2Complex',
  'all': {'Refinery': -0.003,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.008,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.019,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0058,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.012,
            'RFCC2공장': 0.0,
            '아로마틱2공장': -0.052,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-30400',
  'unit_name': '#2 VDU',
  'unit_desc': 'EDC 182,000',
  'edc': 182000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.004,
          '#1Complex': -0.008,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.025,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-16600',
  'unit_name': 'HGO Splitter',
  'unit_desc': 'EDC 22,000',
  'edc': 22000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0005,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.003,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-20200',
  'unit_name': '#1 RFCC',
  'unit_desc': 'EDC 611,085',
  'edc': 611085,
  'complex': '#1Complex',
  'all': {'Refinery': -0.015,
          '#1Complex': -0.026,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.079,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0272,
            '#1Complex': -0.054,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': -0.204,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-101200',
  'unit_name': '#2 RFCC',
  'unit_desc': 'EDC 932,400',
  'edc': 932400,
  'complex': '#2Complex',
  'all': {'Refinery': -0.023,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.054,
          'RFCC2공장': -0.152,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0414,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.084,
            'RFCC2공장': -0.191,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-30200',
  'unit_name': 'HYC FH',
  'unit_desc': 'EDC 510,000',
  'edc': 510000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.012,
          '#1Complex': -0.022,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.069,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0227,
            '#1Complex': -0.045,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': -0.11,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7200',
  'unit_name': '#1 Aromizer',
  'unit_desc': 'EDC 234,000',
  'edc': 234000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.006,
          '#1Complex': -0.01,
          '정유/윤활/아로공장': -0.027,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0104,
            '#1Complex': -0.021,
            '정유/윤활/아로공장': -0.063,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-47200',
  'unit_name': '#2 Aromizer',
  'unit_desc': 'EDC 317,200',
  'edc': 317200,
  'complex': '#2Complex',
  'all': {'Refinery': -0.008,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.018,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.045,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0141,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.028,
            'RFCC2공장': 0.0,
            '아로마틱2공장': -0.126,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-31100',
  'unit_name': '#1 HMP',
  'unit_desc': 'EDC 330,167',
  'edc': 330167,
  'complex': '#1Complex',
  'all': {'Refinery': -0.008,
          '#1Complex': -0.014,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.045,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-21100',
  'unit_name': '#2 HMP',
  'unit_desc': 'EDC 330,167',
  'edc': 330167,
  'complex': '#1Complex',
  'all': {'Refinery': -0.008,
          '#1Complex': -0.014,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.043,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-51100',
  'unit_name': '#3 HMP',
  'unit_desc': 'EDC 330,167',
  'edc': 330167,
  'complex': '#1Complex',
  'all': {'Refinery': -0.008,
          '#1Complex': -0.014,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.043,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-31150',
  'unit_name': '#1 Off Gas PSA',
  'unit_desc': 'EDC 18,173',
  'edc': 18173,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.002,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7810',
  'unit_name': '#1 PSA',
  'unit_desc': 'EDC 15,005',
  'edc': 15005,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.002,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7830',
  'unit_name': '#2 PSA',
  'unit_desc': 'EDC 15,005',
  'edc': 15005,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.002,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'X-47200',
  'unit_name': '#2 ARO PSA',
  'unit_desc': 'EDC 44,849',
  'edc': 44849,
  'complex': '#2Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.003,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.006,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7850',
  'unit_name': '#2 Off-gas PSA',
  'unit_desc': 'EDC 24,056',
  'edc': 24056,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0006,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.003,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-21200',
  'unit_name': '#1 MTBE',
  'unit_desc': 'EDC 22,000',
  'edc': 22000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0005,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.003,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '폴리머공장',
  'unit_code': 'U-102200',
  'unit_name': '#2 MTBE',
  'unit_desc': 'EDC 73,304',
  'edc': 73304,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.004,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': -0.018},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-21300',
  'unit_name': '#1 Alkylation',
  'unit_desc': 'EDC 114,330',
  'edc': 114330,
  'complex': '#1Complex',
  'all': {'Refinery': -0.003,
          '#1Complex': -0.005,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.015,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-102500',
  'unit_name': '#2 Alkylation',
  'unit_desc': 'EDC 183,150',
  'edc': 183150,
  'complex': '#1Complex',
  'all': {'Refinery': -0.004,
          '#1Complex': -0.008,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.024,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-102700',
  'unit_name': 'C4 Isomerization',
  'unit_desc': 'EDC 28,600',
  'edc': 28600,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0007,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.004,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-1800',
  'unit_name': '#1 GHDS',
  'unit_desc': 'EDC 11,900',
  'edc': 11900,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0003,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.001,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7100',
  'unit_name': 'NHDS',
  'unit_desc': 'EDC 72,148',
  'edc': 72148,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.003,
          '정유/윤활/아로공장': -0.008,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-31300',
  'unit_name': 'NHDS',
  'unit_desc': 'EDC 21,300',
  'edc': 21300,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0005,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.003,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-1810',
  'unit_name': '#2 GHDS',
  'unit_desc': 'EDC 20,400',
  'edc': 20400,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.002,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-20850',
  'unit_name': 'SHU',
  'unit_desc': 'EDC 3,000',
  'edc': 3000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0001,
          '#1Complex': -0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-47100',
  'unit_name': 'NHDS',
  'unit_desc': 'EDC 95,108',
  'edc': 95108,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.006,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.014,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-102800SHU',
  'unit_name': '#3 GHDS - SHU',
  'unit_desc': 'EDC 34,702',
  'edc': 34702,
  'complex': '#2Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': -0.006,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-102800HDS',
  'unit_name': '#3 GHDS - HDS',
  'unit_desc': 'EDC 7,834',
  'edc': 7834,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.0,
          'RFCC2공장': -0.001,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-102900HDS',
  'unit_name': 'BEU - HDS',
  'unit_desc': 'EDC 3,649',
  'edc': 3649,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.0,
          'RFCC2공장': -0.001,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-1300',
  'unit_name': '#1 HDS',
  'unit_desc': 'EDC 41,400',
  'edc': 41400,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.005,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-11300',
  'unit_name': '#2 HDS',
  'unit_desc': 'EDC 72,000',
  'edc': 72000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.003,
          '정유/윤활/아로공장': -0.008,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-16300',
  'unit_name': '#3 HDS',
  'unit_desc': 'EDC 110,000',
  'edc': 110000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.003,
          '#1Complex': -0.005,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.015,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-20100',
  'unit_name': 'MHC',
  'unit_desc': 'EDC 150,000',
  'edc': 150000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.004,
          '#1Complex': -0.006,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.02,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '폴리머공장',
  'unit_code': 'U-102300',
  'unit_name': 'C4 SHU',
  'unit_desc': 'EDC 26,460',
  'edc': 26460,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0006,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': -0.006},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-30100',
  'unit_name': '#1 RHDS',
  'unit_desc': 'EDC 205,101',
  'edc': 205101,
  'complex': '#1Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': -0.009,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.028,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0091,
            '#1Complex': -0.018,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': -0.044,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-50100',
  'unit_name': '#2 RHDS',
  'unit_desc': 'EDC 210,848',
  'edc': 210848,
  'complex': '#1Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': -0.009,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.027,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0094,
            '#1Complex': -0.019,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': -0.07,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-101100',
  'unit_name': '#3 RHDS',
  'unit_desc': 'EDC 408,000',
  'edc': 408000,
  'complex': '#2Complex',
  'all': {'Refinery': -0.01,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.024,
          'RFCC2공장': -0.067,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0181,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.037,
            'RFCC2공장': -0.083,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7500',
  'unit_name': '#1 Sulfolane',
  'unit_desc': 'EDC 29,824',
  'edc': 29824,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0007,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.003,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-7600',
  'unit_name': '#2 Sulfolane',
  'unit_desc': 'EDC 30,482',
  'edc': 30482,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0007,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.004,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-47500',
  'unit_name': 'GT-BTX',
  'unit_desc': 'EDC 85,804',
  'edc': 85804,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.005,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.012,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-102900Ext',
  'unit_name': 'BEU - Extraction',
  'unit_desc': 'EDC 18,336',
  'edc': 18336,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.001,
          'RFCC2공장': -0.003,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-40100',
  'unit_name': 'PxMax',
  'unit_desc': 'EDC 77,182',
  'edc': 77182,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.003,
          '정유/윤활/아로공장': -0.009,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-40200',
  'unit_name': 'TAC-9',
  'unit_desc': 'EDC 73,102',
  'edc': 73102,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.003,
          '정유/윤활/아로공장': -0.008,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-48200',
  'unit_name': 'Transplus',
  'unit_desc': 'EDC 158,266',
  'edc': 158266,
  'complex': '#2Complex',
  'all': {'Refinery': -0.004,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.009,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.022,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-40500',
  'unit_name': 'Isolene',
  'unit_desc': 'EDC 190,880',
  'edc': 190880,
  'complex': '#1Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': -0.008,
          '정유/윤활/아로공장': -0.022,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-48500',
  'unit_name': 'XYMAX',
  'unit_desc': 'EDC 224,339',
  'edc': 224339,
  'complex': '#2Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.013,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.032,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-40400',
  'unit_name': '#1 Eluxyl',
  'unit_desc': 'EDC 209,646',
  'edc': 209646,
  'complex': '#1Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': -0.009,
          '정유/윤활/아로공장': -0.024,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0093,
            '#1Complex': -0.018,
            '정유/윤활/아로공장': -0.056,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-48400',
  'unit_name': '#2 Eluxyl',
  'unit_desc': 'EDC 243,713',
  'edc': 243713,
  'complex': '#2Complex',
  'all': {'Refinery': -0.006,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.014,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.035,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0108,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.022,
            'RFCC2공장': 0.0,
            '아로마틱2공장': -0.096,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'T-102104',
  'unit_name': 'ERU - Deethanzier',
  'unit_desc': 'EDC 93,566',
  'edc': 93566,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.005,
          'RFCC2공장': -0.015,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'U-20600',
  'unit_name': 'PRU',
  'unit_desc': 'EDC 29,159',
  'edc': 29159,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0007,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.004,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'T-101603',
  'unit_name': 'PRU - Propane/Propylene Splitter',
  'unit_desc': 'EDC 84,971',
  'edc': 84971,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.005,
          'RFCC2공장': -0.014,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'T-102503',
  'unit_name': '#2 Alkylation - Deisobutanizer',
  'unit_desc': 'EDC 25,300',
  'edc': 25300,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0006,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.003,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-40203',
  'unit_name': 'Deheptanizer',
  'unit_desc': 'EDC 27,078',
  'edc': 27078,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.003,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'T-16101',
  'unit_name': 'Atmospheric Tower',
  'unit_desc': 'EDC 11,980',
  'edc': 11980,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0003,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.002,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'T-20851',
  'unit_name': 'SHU - LLCN Splitter',
  'unit_desc': 'EDC 31,500',
  'edc': 31500,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.004,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'T-20852',
  'unit_name': 'SHU - MLCN Splitter',
  'unit_desc': 'EDC 18,000',
  'edc': 18000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.002,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'T-102802',
  'unit_name': '#3 GHDS - MCN splitter',
  'unit_desc': 'EDC 20,930',
  'edc': 20930,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0005,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.001,
          'RFCC2공장': -0.003,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7501',
  'unit_name': 'Reformate Splitter',
  'unit_desc': 'EDC 56,368',
  'edc': 56368,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.007,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'T-48301',
  'unit_name': 'Reformate Splitter',
  'unit_desc': 'EDC 81,701',
  'edc': 81701,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.005,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.012,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7508',
  'unit_name': 'Benzene Column',
  'unit_desc': 'EDC 9,299',
  'edc': 9299,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0002,
          '#1Complex': -0.0,
          '정유/윤활/아로공장': -0.001,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7608',
  'unit_name': 'Benzene Column',
  'unit_desc': 'EDC 9,012',
  'edc': 9012,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0002,
          '#1Complex': -0.0,
          '정유/윤활/아로공장': -0.001,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-40102',
  'unit_name': 'Benzene Column',
  'unit_desc': 'EDC 36,877',
  'edc': 36877,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.004,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'T-48101',
  'unit_name': 'Benzene Column',
  'unit_desc': 'EDC 101,916',
  'edc': 101916,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.006,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.014,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-40103',
  'unit_name': 'Toluene Column',
  'unit_desc': 'EDC 33,937',
  'edc': 33937,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.004,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'T-48102',
  'unit_name': 'Toluene Column',
  'unit_desc': 'EDC 95,197',
  'edc': 95197,
  'complex': '#2Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.006,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.014,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7509',
  'unit_name': 'Toluene Column',
  'unit_desc': 'EDC 7,722',
  'edc': 7722,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0002,
          '#1Complex': -0.0,
          '정유/윤활/아로공장': -0.001,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7609',
  'unit_name': 'Toluene Column',
  'unit_desc': 'EDC 8,027',
  'edc': 8027,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0002,
          '#1Complex': -0.0,
          '정유/윤활/아로공장': -0.001,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-7502',
  'unit_name': 'Xylene Rerun Column',
  'unit_desc': 'EDC 44,850',
  'edc': 44850,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.005,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-40301',
  'unit_name': 'Xylene Rerun Column',
  'unit_desc': 'EDC 162,663',
  'edc': 162663,
  'complex': '#1Complex',
  'all': {'Refinery': -0.004,
          '#1Complex': -0.007,
          '정유/윤활/아로공장': -0.019,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'T-48302',
  'unit_name': 'Xylene Rerun Column',
  'unit_desc': 'EDC 277,503',
  'edc': 277503,
  'complex': '#2Complex',
  'all': {'Refinery': -0.007,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.016,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.039,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'T-40201',
  'unit_name': 'Heavy Aromatics Column',
  'unit_desc': 'EDC 22,042',
  'edc': 22042,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.003,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'T-48201',
  'unit_name': 'Heavy Aromatics Column',
  'unit_desc': 'EDC 42,257',
  'edc': 42257,
  'complex': '#2Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.006,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC1공장',
  'unit_code': 'X-20501',
  'unit_name': 'DeSOx',
  'unit_desc': 'EDC 18,815',
  'edc': 18815,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0005,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': -0.002,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'X-101503',
  'unit_name': 'DeSOx',
  'unit_desc': 'EDC 32,623',
  'edc': 32623,
  'complex': '#2Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': -0.005,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'X-7201',
  'unit_name': 'U6 - Cryogenic LPG Recovery',
  'unit_desc': 'EDC 18,315',
  'edc': 18315,
  'complex': '#1Complex',
  'all': {'Refinery': -0.0004,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.002,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '아로마틱2공장',
  'unit_code': 'U-47000',
  'unit_name': 'U6 - Cryogenic LPG Recovery',
  'unit_desc': 'EDC 29,958',
  'edc': 29958,
  'complex': '#2Complex',
  'all': {'Refinery': -0.0007,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': 0.0,
          '아로마틱2공장': -0.004,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'RFCC2공장',
  'unit_code': 'U-102100',
  'unit_name': 'U6 - Cryogenic LPG Recovery',
  'unit_desc': 'EDC 40,317',
  'edc': 40317,
  'complex': '#2Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.002,
          'RFCC2공장': -0.007,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-2100',
  'unit_name': '#1 VDU',
  'unit_desc': 'EDC 56,000',
  'edc': 56000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.007,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-2200',
  'unit_name': 'SDA',
  'unit_desc': 'EDC 55,000',
  'edc': 55000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': -0.006,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-2400',
  'unit_name': 'MEK Dewaxing',
  'unit_desc': 'EDC 86,000',
  'edc': 86000,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.004,
          '정유/윤활/아로공장': -0.01,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-2600',
  'unit_name': '2nd HDT',
  'unit_desc': 'EDC 31,030',
  'edc': 31030,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.001,
          '정유/윤활/아로공장': -0.004,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'U-30600',
  'unit_name': 'HYC SH',
  'unit_desc': 'EDC 191,400',
  'edc': 191400,
  'complex': '#1Complex',
  'all': {'Refinery': -0.005,
          '#1Complex': -0.008,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.026,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0085,
            '#1Complex': -0.017,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': -0.041,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '정유/윤활/아로공장',
  'unit_code': 'U-2300',
  'unit_name': '1st HDT',
  'unit_desc': 'EDC 96,287',
  'edc': 96287,
  'complex': '#1Complex',
  'all': {'Refinery': -0.002,
          '#1Complex': -0.004,
          '정유/윤활/아로공장': -0.011,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': -0.0043,
            '#1Complex': -0.008,
            '정유/윤활/아로공장': -0.026,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': 'HYC공장',
  'unit_code': 'T-30604',
  'unit_name': '3nd Vacuum Tower',
  'unit_desc': 'EDC 46,747',
  'edc': 46747,
  'complex': '#1Complex',
  'all': {'Refinery': -0.001,
          '#1Complex': -0.002,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': -0.006,
          'RFCC1공장': 0.0,
          '#2Complex': 0.0,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': 0.0},
  'major': {'Refinery': 0.0,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': 0.0,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': 0.0}},
 {'plant': '폴리머공장',
  'unit_code': 'U-201000',
  'unit_name': 'PP',
  'unit_desc': 'EDC 273,375',
  'edc': 273375,
  'complex': '#2Complex',
  'all': {'Refinery': -0.007,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.016,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': -0.067},
  'major': {'Refinery': -0.0121,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.025,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': -0.074}},
 {'plant': '폴리머공장',
  'unit_code': 'U-202000',
  'unit_name': 'PO',
  'unit_desc': 'EDC 745,200',
  'edc': 745200,
  'complex': '#2Complex',
  'all': {'Refinery': -0.018,
          '#1Complex': 0.0,
          '정유/윤활/아로공장': 0.0,
          'HYC공장': 0.0,
          'RFCC1공장': 0.0,
          '#2Complex': -0.043,
          'RFCC2공장': 0.0,
          '아로마틱2공장': 0.0,
          '폴리머공장': -0.183},
  'major': {'Refinery': -0.0331,
            '#1Complex': 0.0,
            '정유/윤활/아로공장': 0.0,
            'HYC공장': 0.0,
            'RFCC1공장': 0.0,
            '#2Complex': -0.067,
            'RFCC2공장': 0.0,
            '아로마틱2공장': 0.0,
            '폴리머공장': -0.2}}]

PLANT_OPTIONS = [
    "정유/윤활/아로공장",
    "HYC공장",
    "RFCC1공장",
    "RFCC2공장",
    "아로마틱2공장",
    "폴리머공장",
]

SUMMARY_ORDER = [
    "Refinery",
    "#1Complex",
    "정유/윤활/아로공장",
    "HYC공장",
    "RFCC1공장",
    "#2Complex",
    "RFCC2공장",
    "아로마틱2공장",
    "폴리머공장",
]

# =========================================================
# 2) TARGET / CURRENT
# =========================================================
TARGET_MAJOR = {
    "Refinery": 95.6,
    "#1Complex": 96.2,
    "정유/윤활/아로공장": 96.7,
    "HYC공장": 96.4,
    "RFCC1공장": 94.9,
    "#2Complex": 95.1,
    "RFCC2공장": 94.3,
    "아로마틱2공장": 96.7,
    "폴리머공장": 95.2,
}

TARGET_ALL = {
    "Refinery": 96.1,
    "#1Complex": 96.5,
    "정유/윤활/아로공장": 96.7,
    "HYC공장": 97.0,
    "RFCC1공장": 95.9,
    "#2Complex": 95.5,
    "RFCC2공장": 94.6,
    "아로마틱2공장": 96.6,
    "폴리머공장": 95.0,
}

CURRENT_MAJOR = {k: round(v + 0.3, 1) for k, v in TARGET_MAJOR.items()}
CURRENT_ALL = {k: round(v + 0.3, 1) for k, v in TARGET_ALL.items()}

DEFAULT_TARGET = 96.0
DEFAULT_CURRENT = 96.3

# =========================================================
# 3) UI
# =========================================================
st.markdown(
    """
    <style>
    .stApp {
        background: linear-gradient(180deg, #f5f7fb 0%, #eef2f7 100%);
    }

    .block-container {
        max-width: 1400px;
        padding-top: 0.7rem;
        padding-bottom: 1rem;
    }

    .hero-box {
        background: rgba(255,255,255,0.92);
        border: 1px solid #e5e7eb;
        border-radius: 24px;
        padding: 20px 24px;
        box-shadow: 0 8px 24px rgba(15,23,42,0.05);
        margin-bottom: 14px;
    }

    .hero-title {
        font-size: 2.2rem;
        font-weight: 850;
        color: #0f172a;
        margin: 0;
        letter-spacing: -0.04em;
        line-height: 1.05;
    }

    .hero-subtitle {
        font-size: 0.92rem;
        color: #64748b;
        margin-top: 8px;
        line-height: 1.45;
    }

    .section-card {
        background: rgba(255,255,255,0.90);
        border: 1px solid #e7ebf0;
        border-radius: 20px;
        padding: 14px 16px;
        box-shadow: 0 8px 20px rgba(15,23,42,0.04);
        margin-bottom: 14px;
    }

    .section-title {
        font-size: 1rem;
        font-weight: 800;
        color: #0f172a;
        margin-bottom: 4px;
    }

    .section-note {
        font-size: 0.84rem;
        color: #64748b;
        margin-bottom: 10px;
    }

    .metric-box {
        background: linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%);
        border: 1px solid #fdba74;
        border-radius: 18px;
        padding: 14px 16px;
        box-shadow: 0 6px 16px rgba(249,115,22,0.06);
        min-height: 96px;
    }

    .metric-label {
        font-size: 0.84rem;
        font-weight: 700;
        color: #9a3412;
        margin-bottom: 8px;
    }

    .metric-number {
        font-size: 2.05rem;
        font-weight: 850;
        color: #0f172a;
        letter-spacing: -0.04em;
        line-height: 1.0;
    }

    .table-title {
        font-size: 1rem;
        font-weight: 800;
        color: #0f172a;
        margin-bottom: 8px;
    }

    div.stButton > button {
        border-radius: 12px !important;
        font-weight: 700 !important;
        height: 2.25rem !important;
        border: 1px solid #d9e0e8 !important;
        background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%) !important;
        color: #0f172a !important;
        box-shadow: 0 2px 8px rgba(15,23,42,0.04);
        font-size: 0.86rem !important;
    }

    div[data-baseweb="select"] > div {
        border-radius: 12px !important;
        min-height: 40px !important;
        border-color: #d7dee7 !important;
        background: rgba(255,255,255,0.99) !important;
        color: #111827 !important;
        box-shadow: none !important;
    }

    div[data-baseweb="input"] > div {
        border-radius: 12px !important;
        min-height: 40px !important;
        border-color: #d7dee7 !important;
        background: rgba(255,255,255,0.99) !important;
        color: #111827 !important;
        box-shadow: none !important;
    }

    input {
        color: #111827 !important;
        font-size: 0.93rem !important;
    }

    div[data-testid="stVerticalBlock"] > div:empty {
        display: none !important;
    }

    hr {
        display: none !important;
    }

    [data-testid="stMetricDelta"] {
        display: none !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="hero-box">
        <div class="hero-title">S-OIL OA Simulator</div>
        <div class="hero-subtitle">공장 선택 후 해당 Unit과 설명을 선택하고, 정지 일수 및 T&I / Non-T&I 조건에 따라 All / Major 영향을 계산합니다.</div>
    </div>
    """,
    unsafe_allow_html=True,
)

# =========================================================
# 4) HELPERS
# =========================================================
def units_by_plant(plant: str) -> list[str]:
    subset = [row for row in UNIT_DATA if row["plant"] == plant]
    return [
        f'{row["unit_code"]} | {row["unit_name"]} | {row["unit_desc"]}'
        for row in subset
        if str(row["unit_code"]).strip()
    ]

def row_by_unit_display(unit_display: str):
    for row in UNIT_DATA:
        display = f'{row["unit_code"]} | {row["unit_name"]} | {row["unit_desc"]}'
        if display == unit_display:
            return row
    return None

def new_row():
    default_plant = PLANT_OPTIONS[0]
    unit_opts = units_by_plant(default_plant)
    default_unit = unit_opts[0] if unit_opts else ""
    return {"plant": default_plant, "unit": default_unit, "days": 1.0, "mode": "Non-T&I"}

def get_ti_factor(plant_name: str, unit_name: str, mode: str) -> float:
    if mode == "Non-T&I":
        return 1.0
    if plant_name in {"RFCC1공장", "RFCC2공장"}:
        return 1.0 / 3.0
    if unit_name.strip().upper() == "PO":
        return 1.0 / 3.0
    return 1.0 / 4.0

def get_target(label: str, mode: str) -> float:
    if mode == "all":
        return float(TARGET_ALL.get(label, DEFAULT_TARGET))
    return float(TARGET_MAJOR.get(label, DEFAULT_TARGET))

def get_current(label: str, mode: str) -> float:
    if mode == "all":
        return float(CURRENT_ALL.get(label, DEFAULT_CURRENT))
    return float(CURRENT_MAJOR.get(label, DEFAULT_CURRENT))

def prettify_label(label: str) -> str:
    if label == "Refinery":
        return "Refinery"
    if "Complex" in label:
        return "   " + label
    return "      • " + label

def build_summary_df(headers, impact_map, mode: str):
    rows = []
    for h in headers:
        target = get_target(h, mode=mode)
        current = get_current(h, mode=mode)
        impact = float(impact_map.get(h, 0.0))
        forecast = current + impact
        signal = "🔴" if forecast < target else "🟢"
        rows.append({
            "구분": prettify_label(h),
            "Target": f"{target:.1f}",
            "현재 추정": f"{current:.1f}",
            "Forecast Impact": "" if abs(impact) < 1e-12 else f"{impact:,.3f}",
            "변동": f"{forecast:,.2f} {signal}",
            "__raw__": h,
        })
    return pd.DataFrame(rows)

def style_summary_df(df: pd.DataFrame):
    raw_labels = df["__raw__"].tolist()
    display_df = df.drop(columns=["__raw__"]).copy()

    def highlight_rows(row):
        raw_label = raw_labels[row.name]
        if raw_label == "Refinery":
            return ["border:2px solid black; font-weight:700; background-color:#f8fafc"] * len(row)
        return [""] * len(row)

    return (
        display_df.style
        .hide(axis="index")
        .apply(highlight_rows, axis=1)
        .set_table_styles([
            {
                "selector": "table",
                "props": [
                    ("border-collapse", "collapse"),
                    ("width", "100%"),
                    ("font-size", "15px"),
                    ("background-color", "#ffffff"),
                    ("color", "#111827"),
                ],
            },
            {
                "selector": "thead th",
                "props": [
                    ("background-color", "#dfe7f2"),
                    ("color", "#111827"),
                    ("font-size", "15px"),
                    ("font-weight", "700"),
                    ("padding", "10px 10px"),
                    ("text-align", "center"),
                    ("border", "1px solid #cfd8e3"),
                ],
            },
            {
                "selector": "tbody td",
                "props": [
                    ("font-size", "15px"),
                    ("color", "#111827"),
                    ("padding", "9px 10px"),
                    ("border", "1px solid #d7dde6"),
                    ("background-color", "#ffffff"),
                ],
            },
            {
                "selector": "tbody tr:nth-child(even) td",
                "props": [("background-color", "#fafcff")],
            },
        ])
    )

# =========================================================
# 5) SESSION STATE
# =========================================================
if "rows_main" not in st.session_state:
    st.session_state.rows_main = [new_row()]

# =========================================================
# 6) INPUT
# =========================================================
st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.markdown('<div class="section-title">입력</div>', unsafe_allow_html=True)
st.markdown('<div class="section-note">공장을 먼저 선택한 뒤, 오른쪽 Unit 목록에서 해당 공장의 Unit과 설명을 선택하세요.</div>', unsafe_allow_html=True)

top_btn_col, _ = st.columns([0.14, 0.86])
with top_btn_col:
    if st.button("행 추가", use_container_width=True):
        st.session_state.rows_main.append(new_row())
        st.rerun()

delete_idx = None
updated_rows = []

for i, row in enumerate(st.session_state.rows_main):
    c1, c2, c3, c4, c5 = st.columns([0.45, 1.0, 1.8, 0.9, 0.8], gap="small")

    with c1:
        if len(st.session_state.rows_main) > 1:
            if st.button("삭제", key=f"del_{i}", use_container_width=True):
                delete_idx = i

    with c2:
        plant = st.selectbox(
            f"공장 {i+1}",
            PLANT_OPTIONS,
            index=PLANT_OPTIONS.index(row["plant"]) if row["plant"] in PLANT_OPTIONS else 0,
            key=f"plant_{i}",
        )

    unit_options = units_by_plant(plant)
    current_unit = row["unit"] if row["unit"] in unit_options else (unit_options[0] if unit_options else "")

    with c3:
        unit = st.selectbox(
            f"Unit {i+1}",
            unit_options,
            index=unit_options.index(current_unit) if current_unit in unit_options and unit_options else 0,
            key=f"unit_{i}",
        )

    with c4:
        mode = st.selectbox(
            f"구분 {i+1}",
            ["Non-T&I", "T&I"],
            index=["Non-T&I", "T&I"].index(row["mode"]) if row["mode"] in ["Non-T&I", "T&I"] else 0,
            key=f"mode_{i}",
        )

    with c5:
        days = st.number_input(
            f"정지 일수 {i+1}",
            min_value=0.0,
            step=0.1,
            value=float(row["days"]),
            format="%.1f",
            key=f"days_{i}",
        )

    updated_rows.append({
        "plant": plant,
        "unit": unit,
        "days": float(days),
        "mode": mode,
    })

if delete_idx is not None:
    updated_rows.pop(delete_idx)
    st.session_state.rows_main = updated_rows if updated_rows else [new_row()]
    st.rerun()
else:
    st.session_state.rows_main = updated_rows

st.markdown('</div>', unsafe_allow_html=True)

# =========================================================
# 7) CALCULATION
# =========================================================
all_impact_map = {h: 0.0 for h in SUMMARY_ORDER}
major_impact_map = {h: 0.0 for h in SUMMARY_ORDER}

for row in st.session_state.rows_main:
    matched_row = row_by_unit_display(row["unit"])
    if matched_row is None:
        continue

    plant_name = str(matched_row["plant"]).strip()
    unit_name = str(matched_row["unit_name"]).strip()
    factor = get_ti_factor(plant_name, unit_name, row["mode"])

    for h in SUMMARY_ORDER:
        all_impact_map[h] += float(matched_row["all"].get(h, 0.0)) * row["days"] * factor
        major_impact_map[h] += float(matched_row["major"].get(h, 0.0)) * row["days"] * factor

major_refinery = float(major_impact_map.get("Refinery", 0.0))
all_refinery = float(all_impact_map.get("Refinery", 0.0))

# =========================================================
# 8) SUMMARY
# =========================================================
st.subheader("요약")

m1, m2 = st.columns(2, gap="large")
with m1:
    st.markdown(
        f"""
        <div class="metric-box">
            <div class="metric-label">Major Refinery Impact</div>
            <div class="metric-number">{major_refinery:,.3f}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

with m2:
    st.markdown(
        f"""
        <div class="metric-box">
            <div class="metric-label">All Refinery Impact</div>
            <div class="metric-number">{all_refinery:,.3f}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

major_df = build_summary_df(SUMMARY_ORDER, major_impact_map, mode="major")
all_df = build_summary_df(SUMMARY_ORDER, all_impact_map, mode="all")

t1, t2 = st.columns(2, gap="large")
with t1:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="table-title">Major</div>', unsafe_allow_html=True)
    st.dataframe(style_summary_df(major_df), use_container_width=True, hide_index=True)
    st.markdown('</div>', unsafe_allow_html=True)

with t2:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="table-title">All Unit</div>', unsafe_allow_html=True)
    st.dataframe(style_summary_df(all_df), use_container_width=True, hide_index=True)
    st.markdown('</div>', unsafe_allow_html=True)